### ISSUE TITLE
invalid_grant: expired_client_token Auth Grant Flow error

### ISSUE THREAD

**Issue by RajOfficeTroops** [docusign/code-examples-ruby#18]
On running the project after setting the required values :
client_id => Integrator_Key (Same value used for client_secret)

On trying to login to my demo docusign account through the application using authentication grant flow,
I get:
```
OAuth2::Error
invalid_grant: expired_client_token {"error":"invalid_grant","error_description":"expired_client_token"}
```

**Comment by LarryKlugerDS** [comment]
How can we reproduce?
Does this happen each time you restart the application?

**Comment by RajOfficeTroops** [comment]
So after cloning, only change that I have done (apart from setting the required values in application.rb) is:
```
platforms :mswin do 
  gem "wdm", :group => [:development, :test]
end
```

Then If I go to any of the examples and try to use `Authorization Code Grant` for `authenticating with Docusign`, I get the above error

**Comment by LarryKlugerDS** [comment]
Thank you. I have filed internal ticket DEVDOCS-2903 for our development group to investigate.

**Comment by RajOfficeTroops** [comment]
This got resolved by adding a secret key in the Admin Panel and referencing it as client_secret.
Previously client_id and client_secret was kept as same as the Integrator key.
Waiting for [this](https://github.com/docusign/docusign-ruby-client/issues/51) to get resolved.

**Comment by AaronWDS** [comment]
Expired Client Token error can happen because you've received the response code but waited past 10 minutes to use this code to generate your access token.  Based on your comments however, this appears to be with missing credentials on the config file. We did make recent updates to that file which may explain your problem experienced within that time-frame. If you run into any other problems, please open a fresh issue. Thanks again for reporting this.

**Comment by anwarkhan0** [comment]
I am following each step on site guide but I am getting authorized client error and some time expired token error

**Comment by ENeha** [comment]
> 

Yeah...same with me

**Comment by InbarGazit** [comment]
@ENeha please either open a new issue, contact support, or email me to try to help with your issue, I'm not clear what issue you have and not sure how I can help.
