### ISSUE TITLE
Auth URL not available /auth/docusign

### ISSUE THREAD

**Issue by chrisortman** [docusign/code-examples-ruby#24]
Hello, I think this gem is causing a problem.

https://github.com/docusign/code-examples-ruby/blob/38035e660c60751feb4ab11e44bbdd2b38ee48fe/Gemfile#L67

It restricts the `OmniAuth.allowed_request_methods` to `post` which doesn't work because the example does a GET redirect to /auth/docusign.

I think this gem is present because of the CVE.

For folks who find this issue because they're stuck, if you're only working on an example, then you can remove it. If you need to go to production you have to have form that can click a 'login' button and POST to the auth url.

**Comment by LarryKlugerDS** [comment]
Thank you for the problem report.
I have reported it to our engineering group as DEVDOCS-3551

**Comment by InbarGazit** [comment]
This issue has been addressed.
