### ISSUE TITLE
How the omniauth authentication will work in API Version ?

### ISSUE THREAD

**Issue by aliammaar** [docusign/code-examples-ruby#40]
I have cloned the repository on local and able to create template successfully from my local to DocuSign account.
My aim is to provide an endpoint to Podio system where they `POST` the document by URI which I will be then forwarding to DocuSign to create a Template and return the created template_id in json response to source. They will utilize the template with Docmosis.
 
- I am wondering how can I skip the first authentication step and do the authentication with DoucSign account via API calls as Web Service. OR if I can do that authentication from the UI at once only. Is there a mechanism that will fetch the and update the auth token automatically without any user interaction?

- Moreover, I am not sure what is difference between a DocuSign developer account and regular account, Are the templates created in both are classified as belongs to different users?

**Comment by LarryKlugerDS** [comment]
All API calls to DocuSign require an access token. If your app wants to call the DocuSign API and no user is present, then use the JWT grant to obtain an access token.

Re: developer and production accounts: they are two different systems. So you can create templates in the dev account to test your app. But those templates are not available in the production systems--you'll need to copy or re-create them in your production account.

**Comment by Alie-Ammaar** [comment]
@LarryKlugerDS thank you so much for kind information. I really appreciate your quick response.

I am at the stage where I want to move my app to production from development phase.

Can you please guide what configuration I need to change in order to go live.

Thanks again

**Comment by InbarGazit** [comment]
Sorry for the delay @Alie-Ammaar  all information about go-live can be found here - https://developers.docusign.com/platform/go-live/
