### ISSUE TITLE
App fails to start due to nokogiri version issues in Gemfile.lock

### ISSUE THREAD

**Issue by superchris** [docusign/code-examples-ruby#46]
When attempting to start the app with `bundle exec rails`, I get:

```
You have already activated nokogiri 1.11.4, but your Gemfile requires nokogiri 1.11.3. Prepending `bundle exec` to your command may solve this. (Gem::LoadError)
```

It appears that both nokogiri 1.11.3 and 1.11.4 are listed for my platform (linux). Removing the reference to 1.11.3 in Gemfile.lock fixes the issue

**Comment by LarryKlugerDS** [comment]
Thank you for the bug report. I've filed internal report DCM-5975

**Comment by InbarGazit** [comment]
@superchris  is this still a valid issue?
